In [1]:
import torch
temp = torch.randint(0, 5, (3, 1, 5))
temp2 = torch.randint(0, 5, (3, 3, 5))

/home/user/anaconda3/envs/deformable_detr/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [1]:
import MultiScaleDeformableAttention

print(MultiScaleDeformableAttention)

ImportError: libc10.so: cannot open shared object file: No such file or directory

In [3]:
import pickle
import os

def save_rehearsal(rehearsal, dir, task):    
    all_dir = dir  + "ALL_gpu_rehearsal_task_" + str(task)
    if not os.path.exists(dir):
        os.mkdir(dir)
        print(f"Directroy created")

    with open(all_dir, 'wb') as f:
        pickle.dump(rehearsal, f)

tensor([[[1, 4, 3, 3, 4]],

        [[1, 0, 0, 3, 1]],

        [[1, 3, 2, 0, 1]]])
tensor([[[1, 4, 2, 3, 2],
         [4, 3, 1, 1, 0],
         [4, 2, 0, 3, 1]],

        [[1, 3, 1, 1, 2],
         [0, 3, 1, 1, 2],
         [2, 4, 0, 1, 2]],

        [[4, 0, 4, 2, 4],
         [3, 3, 2, 4, 2],
         [4, 4, 3, 4, 3]]])
tensor([[[2, 8, 5, 6, 6],
         [5, 7, 4, 4, 4],
         [5, 6, 3, 6, 5]],

        [[2, 3, 1, 4, 3],
         [1, 3, 1, 4, 3],
         [3, 4, 0, 4, 3]],

        [[5, 3, 6, 2, 5],
         [4, 6, 4, 4, 3],
         [5, 7, 5, 4, 4]]])


In [15]:
temp = temp.repeat(repeats=(1, 2, 1))
print(temp.shape)

torch.Size([3, 4, 5])
